---
#
# Asterisk server installation
# Note: this is built from source, so that we get a more current version
# 
- name: upgrade all packages
  yum:
    name: '*'
    state: latest
- name: Enable EPEL packages
  yum:
    name: epel-release
    state: present
- name: Disable SELinux
  selinux:
    state: disabled
- name: Reboot Server
  command: /sbin/shutdown -r now "Ansible changes require reboot"
- name: Wait for server to finish rebooting
  local_action: wait_for host= "{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300
- name: download latest asterisk # currently version 15.1.5
  get_url:
    url: https://downloads.asterisk.org/pub/telephony/asterisk/asterisk-15-current.tar.gz
    dest: /usr/local/src/
    checksum: sha256:5ab2c80e3cb1a933013415d49dbb100e5d2045aeaf926f8eb0ed3b77460a6d83
- name: Extract asterisk installation
  unarchive:
    src: /usr/local/src/asterisk-15-current.tar.gz
    dest: /usr/local/src/
    remote_src: yes
- name: get path to installation directory
  stat:
    path: /usr/local/src/*
  register: install_path
- name: print variable
  debug:
    var: install_path.stat
    verbosity: 4
- name: Build asterisk from source
  command: "{{ item }} chdir=/usr/local/src/asterisk-15.2.0/"
  with_items:
    - contrib/scripts/install_prereq install
    - ./configure
    - make
    - make uninstall
    - make install
    - make config
    - make samples
    - ldconfig
- name: Start and enable Asterisk service
  service:
    name: asterisk
    state: started
    enabled: yes
- name: open port 5060 (sip) in firewalld
  firewalld:
    zone: public
    service: sip
    permanent: true
    state: enabled
- name: restart firewalld to apply changes
  service:
    name: firewalld
    state: restarted
- name: copy configs to the asterisk box
  copy:
    src: "{{ item }}"
    dest: /etc/asterisk/
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_fileglob:
    - home/thomas/ansible/voip_deploy/insall/roles/asterisk/configs/*" # all files in this directory will be copied over
- name: restart asterisk service
  service:
    name: asterisk
    state: restarted
- name: reload dialplan and pjsip module
  command: "{{ item }}"
  with_items:
    - asterisk -x "dialplan reload"
    - asterisk -x "pjsip reload"

